mongo:
  enabled: true
  user: "root"
  host: "localhost"
  port: 27017
  database: "crates"
  authentication:
    enabled: true
    auth: "admin"
    password: ""

server: "KitPvP"

kill: true
vote: true